# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfejs.ui'
#
# Created: Wed Feb  9 22:01:48 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!


from QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
from GUI_AKCJE import *
class Ui_MainWindow(object,GUI_AKCJE):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 715)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 40, 121, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 220, 121, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 200, 121, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 80, 121, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 60, 121, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 100, 121, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 20, 121, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1150, 10, 81, 16))
        self.label.setObjectName("label")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(1100, 190, 171, 211))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 169, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtGui.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 20, 171, 191))
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(40, 0, 101, 16))
        self.label_2.setObjectName("label_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1100, 440, 171, 231))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 121, 20))
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 320, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 131, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_13 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 140, 121, 21))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 120, 121, 21))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_16 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(1100, 80, 171, 20))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(1180, 420, 91, 21))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(1180, 400, 51, 21))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(1230, 400, 41, 21))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(1100, 420, 81, 21))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(1100, 400, 81, 21))
        self.pushButton_21.setObjectName("pushButton_21")
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(350, 0, 601, 31))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_10 = QtGui.QPushButton(self.frame_3)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 0, 61, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.textEdit = QtGui.QTextEdit(self.frame_3)
        self.textEdit.setGeometry(QtCore.QRect(110, 0, 61, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 41, 31))
        self.label_6.setObjectName("label_6")
        self.pushButton_9 = QtGui.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(290, 0, 85, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalSlider = QtGui.QSlider(self.frame_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(450, 10, 101, 19))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton_11 = QtGui.QPushButton(self.frame_3)
        self.pushButton_11.setGeometry(QtCore.QRect(550, 0, 51, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(390, 10, 41, 16))
        self.label_7.setObjectName("label_7")
        self.pushButton_26 = QtGui.QPushButton(self.frame_3)
        self.pushButton_26.setGeometry(QtCore.QRect(170, 0, 41, 31))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtGui.QPushButton(self.frame_3)
        self.pushButton_27.setGeometry(QtCore.QRect(210, 0, 41, 31))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtGui.QPushButton(self.frame_3)
        self.pushButton_28.setGeometry(QtCore.QRect(250, 0, 41, 31))
        self.pushButton_28.setObjectName("pushButton_28")
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(950, 0, 151, 31))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.label_9.setObjectName("label_9")
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.frame_4)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(80, 0, 31, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_12 = QtGui.QPushButton(self.frame_4)
        self.pushButton_12.setGeometry(QtCore.QRect(110, 0, 41, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_22 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(0, 240, 121, 21))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 260, 121, 21))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(0, 280, 121, 21))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(0, 300, 121, 21))
        self.pushButton_25.setObjectName("pushButton_25")
        self.qvtkWidget = QVTKRenderWindowInteractor(self.centralwidget)
        self.qvtkWidget.setGeometry(QtCore.QRect(130, 30, 971, 641))
        self.qvtkWidget.setObjectName("qvtkWidget")
        self.kurlrequester = KUrlRequester(self.centralwidget)
        self.kurlrequester.setGeometry(QtCore.QRect(130, 0, 201, 31))
        self.kurlrequester.setObjectName("kurlrequester")
        self.listWidget_2 = QtGui.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(1100, 30, 171, 51))
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_29 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(1220, 160, 51, 31))
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1110, 100, 121, 20))
        self.label_10.setObjectName("label_10")
        self.kintnuminput = KIntNumInput(self.centralwidget)
        self.kintnuminput.setGeometry(QtCore.QRect(1160, 120, 31, 21))
        self.kintnuminput.setObjectName("kintnuminput")
        self.kintnuminput_2 = KIntNumInput(self.centralwidget)
        self.kintnuminput_2.setGeometry(QtCore.QRect(1190, 120, 31, 21))
        self.kintnuminput_2.setObjectName("kintnuminput_2")
        self.kintnuminput_4 = KIntNumInput(self.centralwidget)
        self.kintnuminput_4.setGeometry(QtCore.QRect(1160, 140, 31, 21))
        self.kintnuminput_4.setObjectName("kintnuminput_4")
        self.kintnuminput_5 = KIntNumInput(self.centralwidget)
        self.kintnuminput_5.setGeometry(QtCore.QRect(1190, 140, 31, 21))
        self.kintnuminput_5.setObjectName("kintnuminput_5")
        self.kintnuminput_7 = KIntNumInput(self.centralwidget)
        self.kintnuminput_7.setGeometry(QtCore.QRect(1160, 160, 31, 21))
        self.kintnuminput_7.setObjectName("kintnuminput_7")
        self.kintnuminput_8 = KIntNumInput(self.centralwidget)
        self.kintnuminput_8.setGeometry(QtCore.QRect(1190, 160, 31, 21))
        self.kintnuminput_8.setObjectName("kintnuminput_8")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1130, 120, 21, 16))
        self.label_8.setObjectName("label_8")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1130, 140, 21, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1130, 160, 21, 16))
        self.label_12.setObjectName("label_12")
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 160, 121, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_15 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 180, 121, 21))
        self.pushButton_15.setObjectName("pushButton_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1270, 23))
        self.menubar.setObjectName("menubar")
        self.menuInput = QtGui.QMenu(self.menubar)
        self.menuInput.setObjectName("menuInput")
        self.menuOutput = QtGui.QMenu(self.menubar)
        self.menuOutput.setObjectName("menuOutput")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_vtk_file = QtGui.QAction(MainWindow)
        self.actionImport_vtk_file.setObjectName("actionImport_vtk_file")
        self.actionImport_dat_file = QtGui.QAction(MainWindow)
        self.actionImport_dat_file.setObjectName("actionImport_dat_file")
        self.actionSave_as_JPEG = QtGui.QAction(MainWindow)
        self.actionSave_as_JPEG.setObjectName("actionSave_as_JPEG")
        self.actionAutor = QtGui.QAction(MainWindow)
        self.actionAutor.setObjectName("actionAutor")
        self.actionWersja = QtGui.QAction(MainWindow)
        self.actionWersja.setObjectName("actionWersja")
        self.actionLinki = QtGui.QAction(MainWindow)
        self.actionLinki.setObjectName("actionLinki")
        self.actionBackground_color = QtGui.QAction(MainWindow)
        self.actionBackground_color.setObjectName("actionBackground_color")
        self.actionWork_space = QtGui.QAction(MainWindow)
        self.actionWork_space.setObjectName("actionWork_space")
        self.actionExport_properties = QtGui.QAction(MainWindow)
        self.actionExport_properties.setObjectName("actionExport_properties")
        self.menuInput.addAction(self.actionImport_vtk_file)
        self.menuInput.addAction(self.actionImport_dat_file)
        self.menuOutput.addAction(self.actionSave_as_JPEG)
        self.menuSettings.addAction(self.actionBackground_color)
        self.menuSettings.addAction(self.actionWork_space)
        self.menuSettings.addAction(self.actionExport_properties)
        self.menuHelp.addAction(self.actionAutor)
        self.menubar.addAction(self.menuInput.menuAction())
        self.menubar.addAction(self.menuOutput.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.connections()

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Isosurface", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "XYZ Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "XY Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Mat Plot 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Layers, Dots", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Outline", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Data Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Rendered Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Object Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Function options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Visualization functions", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("MainWindow", "Sphere Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MainWindow", "Scalar Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MainWindow", "Delete Data Object", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("MainWindow", "Hide", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_19.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20.setText(QtGui.QApplication.translate("MainWindow", "Delete All", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_21.setText(QtGui.QApplication.translate("MainWindow", "New window", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "Set View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "Reset Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_26.setText(QtGui.QApplication.translate("MainWindow", "XView", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_27.setText(QtGui.QApplication.translate("MainWindow", "YView", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_28.setText(QtGui.QApplication.translate("MainWindow", "ZView", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Magnification", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("MainWindow", "Photo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_22.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_23.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_24.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_25.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_29.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Shrink numerical box", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Nx", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Ny", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Nz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Vector Field", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MainWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInput.setTitle(QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOutput.setTitle(QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_vtk_file.setText(QtGui.QApplication.translate("MainWindow", "Open vtk file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_dat_file.setText(QtGui.QApplication.translate("MainWindow", "Open dat file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as_JPEG.setText(QtGui.QApplication.translate("MainWindow", "Export format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutor.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWersja.setText(QtGui.QApplication.translate("MainWindow", "Wersja", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLinki.setText(QtGui.QApplication.translate("MainWindow", "Linki", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackground_color.setText(QtGui.QApplication.translate("MainWindow", "Background color", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWork_space.setText(QtGui.QApplication.translate("MainWindow", "Work space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_properties.setText(QtGui.QApplication.translate("MainWindow", "Export properties", None, QtGui.QApplication.UnicodeUTF8))

from PyKDE4.kio import KUrlRequester
from PyKDE4.kdeui import KIntNumInput

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

